### ISSUE TITLE
XSS mitigation and conforming to license

### ISSUE THREAD

**Issue by aleksasiriski** [GGLVXD/FreeMetasearchApi#1]
Hello there!

I'm a maintainer of the [Hearchco](https://github.com/hearchco) project and would like to inform you that you should update your SvelteKit frontend to the latest version, since it has a XSS bug fixed.

In addition to that, I noticed that you changed the look of your website, which in turn means you've changed the source code of frontend. To conform to the AGPLv3 license, used on both the frontend and the backend, you **MUST** provide a link to the modified source code for your users. Otherwise, at least provide the link to [hearchco](https://github.com/hearchco) if you've only made aesthetic changes (although that still counts as code modification). Needless to say, your fork must also be AGPLv3 licensed.

Happy hearching,
Aleksa

**Comment by GGLVXD** [comment]
I am planning to add multiple buttons including the github repo link button

**Comment by GGLVXD** [comment]
Closing this because i just added a repo link to hearchco github

**Comment by aleksasiriski** [comment]
Thank you very much :)
